apiVersion: v1
kind: Pod
spec:
  containers:
    - name: buildah
      image: hub.predic8.de/p8/buildah:265
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: container-data
        - mountPath: /home/build/.local/share/containers
          name: private-container-data
    - name: kubectl
      image: hub.predic8.de/p8/kubectl:8
      command:
        - cat
      tty: true
  imagePullSecrets:
    - name: p8-hub-credentials
  volumes:
    - name: container-data
      emptyDir: {}
    - name: private-container-data
      emptyDir: {}
