apiVersion: v1
kind: Service
metadata:
  name: pg-op-mon
  namespace: monitoring
spec:
  selector:
    app: pg-op-mon
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-op-mon
  namespace: monitoring
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor"
    predic8.de/scm-path: "/deploy/pg-op-mon.yaml"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-op-mon
  template:
    metadata:
      labels:
        app: pg-op-mon
    spec:
      containers:
        - name: pg-op-mon
          image: hub.predic8.de/p8/pg-op-mon:$BUILD_NUMBER
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 5
          env:
            - name: TZ
              value: "Europe/Berlin"
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: p8-hub-credentials
