kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  namespace: monitoring
  name: pg-op-mon
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "statefulsets"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  name: pg-op-mon
  namespace: monitoring
subjects:
  - kind: User
    name: system:serviceaccount:monitoring:pg-op-mon
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pg-op-mon
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  name: monitoring-pg-op-mon
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["acid.zalan.do"]
    resources: ["postgresqls"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "watch", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  name: monitoring-pg-op-mon-binding
subjects:
  - kind: User
    name: system:serviceaccount:monitoring:pg-op-mon
roleRef:
  kind: ClusterRole
  name: monitoring-pg-op-mon
  apiGroup: rbac.authorization.k8s.io
