apiVersion: v1
kind: Service
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  name: pg-op-mon
  namespace: monitoring
spec:
  selector:
    app: pg-op-mon
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

---

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  name: pg-op-mon
  namespace: monitoring

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    predic8.de/scm: "https://github.com/membrane/postgres-operator-monitor.git"
    predic8.de/scm-path: "kubernetes/template.yaml"
  name: pg-op-mon
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-op-mon
  template:
    metadata:
      labels:
        app: pg-op-mon
    spec:
      containers:
        - name: pg-op-mon
          image: predic8/postgres-operator/monitor:1
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 5
            failureThreshold: 9
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"
      serviceAccountName: pg-op-mon
#      imagePullSecrets:
#        - name: p8-hub-credentials
